Working

diff --git a/mkmail b/mkmail
--- a/mkmail
+++ b/mkmail
@@ -1,4 +1,4 @@
-### echo "ABORTING" ; exit 99
+echo "ABORTING" ; exit 99
 
 
 if [ ! -e /etc/hosts.bak ]
