Fixup

diff --git a/mkmail b/mkmail
--- a/mkmail
+++ b/mkmail
@@ -1,6 +1,8 @@
-echo "ABORTING" ; exit 99
+# echo "ABORTING" ; exit 99
 
+clear; echo -e "\n \n Setting up email "; read -p "<ENTER> to continue, ^C to abort" trash
 
+# Check to see if the system has had the domainname set
 if [ ! -e /etc/hosts.bak ]
 then
 	read -p  'Enter domain name: ' domainname
@@ -10,7 +12,6 @@ then
 	sed -i 's/localhost/'$domainname'/g' /etc/hosts
 	sed -i 's/localhost/'$domainname'/g' /etc/hostname
 
-	read -p "Enter desired Msql Password: " mypass
 	echo "Rebooting the system for changes to take effect"
 	read -p "Press enter to reboot , press ^C to abort"; # shutdown -r now
 else
@@ -18,6 +19,18 @@ else
 	domainname=`hostname`
 	echo $domainname
 fi
+
+read -p "Enter desired Msql Password: " mypass
+read -p "re-enter desired Msql Password: " mypass2
+	if [ -z $mypass ] || [ -z $mypass2 ]
+		then
+		clear;echo -e "\a***************************\n* Please enter a password *\n***************************\n"; exit 99
+	fi
+
+	if [ $mypass != $mypass2 ]	
+		then
+		echo -e "\a******password mismatch******\n" ; exit 99
+	fi
 
 # debconf-set-selections <<< "postfix postfix/mailname string $domainname"
 # sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password your_password'
